# The database to be used. Currently sqlite, postgres and mysql
# are supported. The general syntax for the url is:
# DB_TYPE://USERNAME:PASSWORD@HOST:PORT/DB_NAME?PARAM1=value&PARAM2=value
#
# Example for postgres:
#   postgres://postgres:pass@db.host:5432/somedb
#
# Example for mysql:
#   mysql://myuser:mypass:pass@db.host:3306/somedb
#
# Example for sqlite:
#   sqlite://data/db.sqlite
#   sqlite://:memory: (for the in memory version of sqlite)
db_url: !ENV ${DIGICUBES_DATABASE_URL}

# The port, ther server is listening on
port: 3548

# Secret to be used to encrypt data. It is
# not recommended to store your secret in this
# configuration file. Only if you run the server
# in development or testmode. For production mode
# store your secret in an environment variable.
secret: !ENV ${DIGICUBES_SECRET} 
